"""Tree-recording simulation + counterfactual prune.

`model.simulate` is the calibration path and records no genealogy. This module adds the
intervention tree/prune machinery on top of it, rather than replacing it.

`simulate_tree` is a LINE-FAITHFUL copy of `model.simulate` with recording added and
**zero extra RNG draws**, so `simulate` and `simulate_tree` produce identical trees at
the same (theta, seed) by construction. Keeping it line-faithful is what keeps this copy
in sync with the original: any divergence silently corrupts averted burden.

Why a tree at all: offspring existence depends on the parent's `iso_cutoff` and
`safe_burial` (the `keep` mask in `simulate`). An intervention can only make isolation
EARLIER and safe burial MORE likely, so the intervened tree is always a SUBTREE of the
SQ tree. Recording the SQ tree plus each infection's (parent, gi, is_bur) therefore
lets us evaluate any counterfactual by removal alone — no re-simulation, and common
random numbers are preserved so averted burden is a clean paired difference.

Prune approximation: `aware_day` is cross-generation state computed inside the
simulation loop, so a prune cannot propagate an intervention's awareness
cascade to later generations. The shipped placement summaries therefore price
direct isolation and burial effects on a common tree; they do not re-simulate a
second-order awareness response to infections averted in non-machine zones.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from scipy.stats import nbinom as _nbinom

from .model import (
    Params,
    _confirm_with_capacity,
    _decayed_driver,
    _draw_nuanced_u_tail,
    _nuanced_iso_burial,
    nat_scale,
)

U_KEYS = ("pcr", "clin", "fclin", "presump", "conf", "cadaver", "refer")


def simulate_tree(
    params: Params,
    zones: list[str],
    mobility_out: np.ndarray,
    served_from_day: np.ndarray,
    horizon_day: int,
    rng: np.random.Generator,
    max_infections: int = 200_000,
    collect_high_from_day: np.ndarray | None = None,
    confirm_capacity: tuple | None = None,
    queue_query_days: np.ndarray | None = None,
    care_destination: np.ndarray | None = None,
    zone_r_mult: np.ndarray | None = None,  # (Z,) multiplier on r_eff
    resume: dict | None = None,
    collect_frontier: bool = False,
) -> dict:
    """As `model.simulate`, but returns a dict of per-infection arrays including the
    recorded uniforms, parent links, generation intervals and detection state needed
    to replay counterfactuals. RNG call sequence is identical to `model.simulate`.

    Two-phase continuation support (so forward branches share a data-conditioned
    history instead of being fresh unconditioned realisations):

      phase 1  simulate_tree(..., horizon_day=cutoff, rng=stored_seed,
                             collect_frontier=True)
               -> the tree is bit-identical to the calibration path, and
                  `state["frontier"]` holds every offspring whose infection time fell
                  PAST the cutoff (generated by the stored stream, i.e. still the
                  direct offspring of data-conditioned parents, but not yet simulated).
      phase 2  simulate_tree(..., horizon_day=full, rng=rng_k, resume=state)
               -> continues from that frontier with a fresh stream. Everything at or
                  before the cutoff is therefore IDENTICAL across continuations; only
                  the future diverges.

    `join_trees` concatenates the two, keeping parent indices global and ordered so the
    prune cascade still works.
    """
    z_index = {z: i for i, z in enumerate(zones)}
    if params.seed_zone not in z_index:
        raise ValueError(f"seed zone {params.seed_zone!r} not in zone set")
    if collect_high_from_day is None:
        raise ValueError(
            "collect_high_from_day is required: (Z,) day each zone becomes lab-served"
        )
    seed_zi = z_index[params.seed_zone]
    Z = len(zones)
    if care_destination is None:
        care_destination = np.arange(Z, dtype=np.int64)
    else:
        care_destination = np.asarray(care_destination, dtype=np.int64)

    if resume is None:
        cur_zone = np.full(params.seed_n, seed_zi, dtype=np.int64)
        cur_tinf = np.full(params.seed_n, float(params.seed_day))
        cur_trace_cut = np.full(params.seed_n, np.inf)
        # global index of each current-generation member, and its parent's global index
        cur_gidx = np.arange(params.seed_n, dtype=np.int64)
        cur_parent = np.full(params.seed_n, -1, dtype=np.int64)
        cur_gi = np.full(params.seed_n, np.nan)  # gi relative to parent t_infect
        cur_isbur = np.zeros(params.seed_n, dtype=bool)
        cur_utrace = np.ones(params.seed_n)
        n_offset = 0
    else:
        f = resume["frontier"]
        cur_zone = f["zone"].copy()
        cur_tinf = f["tinf"].copy()
        cur_trace_cut = f["trace_cut"].copy()
        cur_parent = f["parent"].copy()
        cur_gi = f["gi"].copy()
        cur_isbur = f["is_bur"].copy()
        cur_utrace = f["u_trace"].copy()
        n_offset = int(resume["next_gidx"])
        cur_gidx = np.arange(n_offset, n_offset + cur_zone.size, dtype=np.int64)

    rec_zone, rec_tinf = [], []
    rec_incub, rec_report, rec_died, rec_otd = [], [], [], []
    rec_collected, rec_confirm = [], []
    rec_isolated, rec_isostart, rec_isoend = [], [], []
    rec_referred, rec_care_zone, rec_t_collect_abs = [], [], []
    # --- tree recording ---
    rec_parent, rec_gi, rec_isbur, rec_trec = [], [], [], []
    rec_u = {k: [] for k in U_KEYS}
    rec_turn, rec_local, rec_mhigh, rec_aware, rec_pcrprob = [], [], [], [], []
    rec_isocut, rec_safeburial, rec_tcollect_rel = [], [], []
    rec_utrace, rec_tracecut = [], []
    rec_reff = []

    # (Z,) per-zone multiplier on r_eff (conflict / accessibility heterogeneity)
    if zone_r_mult is None:
        zone_mult = np.ones(Z, dtype=float)
    else:
        zone_mult = np.asarray(zone_r_mult, dtype=float)
        if zone_mult.shape != (Z,):
            raise ValueError(f"zone_r_mult must have shape ({Z},), got {zone_mult.shape}")

    if resume is None:
        tinf_post_by_zone = [np.empty(0, dtype=float) for _ in range(Z)]
        tinf_post_nat = np.empty(0, dtype=float)  # NATIONAL sorted post-recog t_infect
        aware_day = np.full(Z, np.inf)
        zone_conf_count = np.zeros(Z, dtype=int)
        total = 0
        next_gidx = int(params.seed_n)
    else:
        # carry the brake / awareness state forward, else the continuation would start
        # with every zone un-braked and naive, which is not a continuation at all.
        # tinf_post_nat in particular drives the NATIONAL awareness brake, so dropping it
        # would resume every branch with an un-braked COUNTRY, and peripheral spill would
        # be badly overstated.
        tinf_post_by_zone = [a.copy() for a in resume["tinf_post_by_zone"]]
        tinf_post_nat = resume["tinf_post_nat"].copy()
        aware_day = resume["aware_day"].copy()
        zone_conf_count = resume["zone_conf_count"].copy()
        total = int(resume["total"])
        next_gidx = n_offset + int(cur_zone.size)

    frontier = {k: [] for k in ("parent", "gi", "is_bur", "zone", "tinf", "trace_cut", "u_trace")}
    # Generation counter, needed ONLY so the seed-conditioning rider can name the seed
    # pass (`gen == 1`) the way `model.simulate` does. It starts at 0 on a RESUME, so phase 2
    # of a continuation can never re-apply the rider -- there is no index case there, and
    # re-truncating the frontier's NB draws would invent transmission the fit never saw.
    gen = 0
    while cur_zone.size and total < max_infections:
        gen += 1 if resume is None else 0
        n = cur_zone.size
        rec_zone.append(cur_zone)
        rec_tinf.append(cur_tinf)
        rec_parent.append(cur_parent)
        rec_gi.append(cur_gi)
        rec_isbur.append(cur_isbur)
        rec_tracecut.append(cur_trace_cut)
        rec_utrace.append(cur_utrace)  # per-generation, so resume works uniformly
        total += n

        # ---- Hill brake (identical to model.simulate) ----
        # `model.simulate` reads the driver through `_decayed_driver`, which is the same
        # count when `tau_w` is infinite. `tau_w` IS infinite in the shipped config, so the
        # two agree today — the call is made through the same helper anyway so that turning
        # the waning-memory reform on cannot silently diverge here. Note the dtype moves
        # int64 -> float to match `model.simulate`; at tau_w = inf `_decayed_driver` returns
        # `.astype(float)` of the same integer counts, so this is exact, not a rounding change.
        cum_for_parent = np.zeros(n, dtype=float)
        threshold_t = cur_tinf - params.brake_lag_days
        for z in np.unique(cur_zone):
            ts = tinf_post_by_zone[z]
            if ts.size > 0:
                zsel = cur_zone == z
                cum_for_parent[zsel] = _decayed_driver(
                    ts, threshold_t[zsel], params.tau_w, params.response_start_day
                )
        deaths = params.ifr * cum_for_parent
        if params.cum_half > 0:
            ratio = deaths / params.cum_half
            brake = 1.0 / (1.0 + np.power(ratio, params.hill_n))
        else:
            brake = np.where(deaths > 0, 0.0, 1.0)
        # ---- NATIONAL awareness brake (multiplies the local brake) ----
        # Same visible-death units and same lag as the local driver, but counted over
        # the whole country: a zone invaded late is braked by what the country has
        # already seen, not by its own (still empty) toll.
        if params.nat_brake_driver == "calendar":
            if params.nat_half_days > 0:
                elapsed = np.maximum(threshold_t - params.response_start_day, 0.0)
                nat_brake = 1.0 / (
                    1.0 + np.power(elapsed / params.nat_half_days, params.nat_hill_n)
                )
            else:
                nat_brake = np.ones(n)
        elif params.nat_half > 0:
            nat_cum = _decayed_driver(
                tinf_post_nat, threshold_t, params.tau_w, params.response_start_day
            )
            nat_deaths = params.ifr * nat_cum
            nat_brake = 1.0 / (1.0 + np.power(nat_deaths / params.nat_half, params.nat_hill_n))
        else:
            nat_brake = np.ones(n)

        # ---- floor the NATIONAL factor only ----
        # B_nat' = beta + (1-beta)*B_nat. Applied after whichever driver produced nat_brake,
        # so it floors the "calendar" variant identically; a no-op when the national brake is
        # off (floor + (1-floor)*1 == 1). The `> 0` guard keeps beta = 0 bit-identical
        # rather than relying on 0 + 1*x round-tripping exactly.
        # LINE-FAITHFUL COPY of model.simulate.
        if params.nat_floor > 0.0:
            nat_brake = params.nat_floor + (1.0 - params.nat_floor) * nat_brake

        # ---- where the national factor multiplies ----
        # "global" puts the national factor OUTSIDE the bracket, so it scales the braked core
        # and the naive frontier alike; `nat_brake` is 1.0 there by `Params.__post_init__`
        # (nat_half / nat_floor forced to 0), so the two forms cannot be layered by accident.
        #
        # If this branch is missing, every forward branch runs unbraked at R_floor > 1 (median
        # 1.134 under this posterior) and forward burden explodes to roughly the `no_clock`
        # arm's. Note that comparing phase-1 output cannot catch it: `nat_scale` returns
        # exactly 1.0 pre-cutoff whether or not this branch is live.
        #
        # LINE-FAITHFUL COPY of model.simulate.
        if params.nat_brake_placement == "global":
            r_eff = nat_scale(threshold_t, params) * (
                params.R_floor + (params.R0 - params.R_floor) * brake
            )
        else:
            r_eff = params.R_floor + (params.R0 - params.R_floor) * brake * nat_brake
        r_eff[cur_tinf < params.response_start_day] = params.R0
        # Zone heterogeneity scales the whole r_eff (floor included) — a
        # better-served, lower-conflict zone transmits less both before and after braking.
        r_eff = r_eff * zone_mult[cur_zone]
        p_nb = params.k / (params.k + r_eff)

        post_mask = cur_tinf >= params.response_start_day
        if post_mask.any():
            for z in np.unique(cur_zone[post_mask]):
                zmask = (cur_zone == z) & post_mask
                new_ts = cur_tinf[zmask]
                tinf_post_by_zone[z] = (
                    np.sort(new_ts)
                    if tinf_post_by_zone[z].size == 0
                    else np.sort(np.concatenate([tinf_post_by_zone[z], new_ts]))
                )
            # mirror the national driver (one sorted array over all zones)
            tinf_post_nat = np.sort(np.concatenate([tinf_post_nat, cur_tinf[post_mask]]))

        # ---- parent illness timeline + turnaround ----
        incub = rng.lognormal(params.incub_meanlog, params.incub_sdlog, n)
        # Legacy draw retained to preserve the calibrated RNG stream and parity
        # with `model.simulate`; fixed turnarounds below determine confirmation.
        report = rng.exponential(params.report_delay_mean, n)
        onset_day = cur_tinf + incub
        served = served_from_day[cur_zone]
        local = onset_day >= served
        unserved_tt = np.where(
            cur_tinf < params.unserved_switch_day,
            params.unserved_turnaround_early,
            params.unserved_turnaround_late,
        )
        turnaround = np.where(local, params.local_turnaround, unserved_tt)

        machine_high = onset_day >= collect_high_from_day[cur_zone]
        aware_only = (onset_day >= aware_day[cur_zone]) & ~machine_high
        u_pcr = rng.random(n)
        died_p = rng.random(n) < params.ifr
        otd_p = rng.gamma(params.otd_shape, params.otd_scale, n)
        rsh = (params.recovery_mean / params.recovery_sd) ** 2
        rsc = params.recovery_sd**2 / params.recovery_mean
        trec_p = rng.gamma(rsh, rsc, n)
        rec_incub.append(incub)
        rec_report.append(report)
        rec_died.append(died_p)
        rec_otd.append(otd_p)
        rec_trec.append(trec_p)
        u = {"pcr": u_pcr, **_draw_nuanced_u_tail(rng, n, params)}
        pcr_prob = np.where(
            machine_high,
            params.p_pcr_high,
            np.where(aware_only, params.p_pcr_mid, params.p_pcr_low),
        )
        for k in U_KEYS:
            rec_u[k].append(u[k])
        rec_turn.append(turnaround)
        rec_local.append(local)
        rec_mhigh.append(machine_high)
        rec_aware.append(aware_only)
        rec_pcrprob.append(pcr_prob)
        rec_reff.append(r_eff)

        iso_cutoff, safe_burial, t_confirm, got_pcr, _t_presump_eff, end_illness, t_collect_rel = (
            _nuanced_iso_burial(
                params,
                n,
                incub,
                died_p,
                otd_p,
                trec_p,
                cur_tinf,
                turnaround,
                pcr_prob,
                machine_high,
                local,
                u,
            )
        )

        iso_cutoff = np.minimum(iso_cutoff, cur_trace_cut - cur_tinf)
        confirm_abs = cur_tinf + t_confirm
        rec_collected.append(got_pcr)
        rec_isocut.append(iso_cutoff)
        rec_safeburial.append(safe_burial)
        rec_tcollect_rel.append(t_collect_rel)

        referring_zone = care_destination[cur_zone] != cur_zone
        referred_flag = referring_zone & (u["refer"] < params.f_refer)
        care_zone = np.where(referred_flag, care_destination[cur_zone], cur_zone)
        rec_referred.append(referred_flag)
        rec_care_zone.append(care_zone)
        t_collect_abs = cur_tinf + t_collect_rel
        rec_t_collect_abs.append(t_collect_abs)

        if params.noso_boost > 0.0:
            r_eff = np.where(referred_flag, r_eff + params.noso_boost * params.R0, r_eff)
            p_nb = params.k / (params.k + r_eff)
        rec_confirm.append(confirm_abs)

        bed_cap_rel = np.where(
            got_pcr,
            t_confirm + params.bed_stay_post_confirm_days,
            iso_cutoff + params.bed_stay_suspect_days,
        )
        iso_end_rel = np.minimum(bed_cap_rel, end_illness)
        rec_isolated.append(np.isfinite(iso_cutoff))
        rec_isostart.append(cur_tinf + iso_cutoff)
        rec_isoend.append(cur_tinf + iso_end_rel)

        tdet = cur_tinf + t_confirm
        conf = np.isfinite(tdet) & (tdet >= params.response_start_day)
        if conf.any():
            if params.aware_threshold <= 1:
                np.minimum.at(aware_day, cur_zone[conf], tdet[conf])
            else:
                cz = cur_zone[conf]
                ct = tdet[conf]
                order = np.argsort(ct)
                for i in order:
                    z = int(cz[i])
                    zone_conf_count[z] += 1
                    if zone_conf_count[z] == params.aware_threshold and aware_day[z] > ct[i]:
                        aware_day[z] = float(ct[i])

        # ---- offspring ----
        n_off = rng.negative_binomial(params.k, p_nb)
        # ---- seed conditioning ---------------------------------------------------------
        # The index case's own NB draw is conditioned away from zero, matching the cell the
        # posterior was fitted in. This MATTERS: with it off, only ~30% of replayed trees
        # clear a >=500 in-window survivor filter and the rest fizzle to a median of ~1-2
        # infections, so the surviving subset lands roughly 2x lower forward. A replay that
        # skips it is running in a different cell than the fit.
        #
        # LINE-FAITHFUL COPY of model.simulate. The stock draw above still runs first so
        # that with the rule off the RNG stream is untouched.
        if params.seed_u_min is not None and gen == 1:
            u_lo = (
                np.power(p_nb, params.k)
                if params.seed_u_min == "nonzero"
                else np.full(n, float(params.seed_u_min))
            )
            uu = u_lo + (1.0 - u_lo) * rng.random(n)
            n_off = _nbinom.ppf(uu, params.k, p_nb).astype(n_off.dtype)
        total_off = int(n_off.sum())
        if total_off == 0:
            break
        parent_idx = np.repeat(np.arange(n), n_off)

        t_end = np.where(died_p, otd_p, trec_p)[parent_idx]
        live_s = t_end * rng.random(total_off) ** (1.0 / (params.ramp_a + 1.0))
        is_bur = died_p[parent_idx] & (rng.random(total_off) < params.w_burial)
        bur_s = otd_p[parent_idx] + rng.random(total_off) * params.burial_width
        gi = incub[parent_idx] + np.where(is_bur, bur_s, live_s)

        keep = np.where(is_bur, ~safe_burial[parent_idx], gi < iso_cutoff[parent_idx])
        parent_idx = parent_idx[keep]
        gi = gi[keep]
        is_bur_keep = is_bur[keep]
        if parent_idx.size == 0:
            break

        off_tinf = cur_tinf[parent_idx] + gi

        parent_zone = cur_zone[parent_idx]
        jump = rng.random(parent_idx.size) < params.jump_prob
        off_zone = parent_zone.copy()
        if jump.any():
            ji = np.nonzero(jump)[0]
            for z in np.unique(parent_zone[ji]):
                sel = ji[parent_zone[ji] == z]
                w = mobility_out[z]
                if w.sum() <= 0:
                    off_zone[sel] = z
                else:
                    off_zone[sel] = rng.choice(Z, size=sel.size, p=w)

        if params.f_refer > 0.0:
            parent_referred = referred_flag[parent_idx]
            parent_t_col = t_collect_rel[parent_idx]
            born_post_collect = gi > parent_t_col
            relocated = parent_referred & born_post_collect
            if relocated.any():
                off_zone[relocated] = care_destination[parent_zone[relocated]]

        if params.sq_trace_eff > 0.0:
            par_conf = confirm_abs[parent_idx]
            u_tr = rng.random(parent_idx.size)
            traced = np.isfinite(par_conf) & (u_tr < params.sq_trace_eff)
            off_trace_cut = np.where(traced, par_conf + params.sq_trace_lag, np.inf)
        else:
            u_tr = np.ones(parent_idx.size)
            off_trace_cut = np.full(parent_idx.size, np.inf)

        within = off_tinf <= horizon_day
        if collect_frontier and (~within).any():
            # offspring of data-conditioned parents whose infection time falls PAST the
            # cutoff: generated by this (stored) stream but not simulated here. These
            # seed the continuation phase, so every branch shares one history.
            out = ~within
            par_g = cur_gidx[parent_idx][out]
            frontier["parent"].append(par_g)
            frontier["gi"].append(gi[out])
            frontier["is_bur"].append(is_bur_keep[out])
            frontier["zone"].append(off_zone[out])
            frontier["tinf"].append(off_tinf[out])
            frontier["trace_cut"].append(off_trace_cut[out])
            frontier["u_trace"].append(u_tr[out])
        cur_parent = cur_gidx[parent_idx][within]
        cur_gi = gi[within]
        cur_isbur = is_bur_keep[within]
        cur_utrace = u_tr[within]
        cur_zone = off_zone[within]
        cur_tinf = off_tinf[within]
        cur_trace_cut = off_trace_cut[within]
        cur_gidx = np.arange(next_gidx, next_gidx + cur_zone.size, dtype=np.int64)
        next_gidx += cur_zone.size

    def _state():
        fr = {
            k: (
                np.concatenate(v)
                if v
                else np.zeros(
                    0,
                    dtype=(
                        np.int64 if k in ("parent", "zone") else (bool if k == "is_bur" else float)
                    ),
                )
            )
            for k, v in frontier.items()
        }
        return {
            "frontier": fr,
            "tinf_post_by_zone": tinf_post_by_zone,
            "tinf_post_nat": tinf_post_nat,  # national brake driver
            "aware_day": aware_day,
            "zone_conf_count": zone_conf_count,
            "total": total,
            "next_gidx": next_gidx,
            "n_offset": n_offset,
        }

    if not rec_zone:
        return {
            "n": 0,
            "zone_idx": np.zeros(0, np.int64),
            "state": _state(),
            "n_offset": n_offset,
            "gen_sizes": np.zeros(0, dtype=np.int64),
        }

    cat = np.concatenate
    T = {
        "zone_idx": cat(rec_zone),
        "t_infect": cat(rec_tinf),
        "parent": cat(rec_parent),
        "gi": cat(rec_gi),
        "is_bur": cat(rec_isbur),
        "incub": cat(rec_incub),
        "report": cat(rec_report),
        "died": cat(rec_died),
        "otd": cat(rec_otd),
        "trec": cat(rec_trec),
        "turnaround": cat(rec_turn),
        "local": cat(rec_local),
        "machine_high": cat(rec_mhigh),
        "aware_only": cat(rec_aware),
        "pcr_prob": cat(rec_pcrprob),
        "r_eff": cat(rec_reff),
        "sq_iso_cutoff": cat(rec_isocut),
        "sq_safe_burial": cat(rec_safeburial),
        "sq_t_collect_rel": cat(rec_tcollect_rel),
        "sq_confirm_abs": cat(rec_confirm),
        "sq_got_pcr": cat(rec_collected),
        "sq_isolated": cat(rec_isolated),
        "sq_iso_start": cat(rec_isostart),
        "sq_iso_end": cat(rec_isoend),
        "trace_cut": cat(rec_tracecut),
        "care_zone": cat(rec_care_zone),
        "referred": cat(rec_referred),
        "hit_cap": bool(total >= max_infections),
    }
    for k in U_KEYS:
        T[f"u_{k}"] = cat(rec_u[k])
    T["u_trace"] = cat(rec_utrace)
    T["n"] = int(T["zone_idx"].size)
    T["seed_n"] = int(params.seed_n)
    # generation block sizes -> lets the prune cascade vectorise per generation
    # (parent index is always in an EARLIER block, so one ordered pass suffices)
    T["gen_sizes"] = np.array([a.size for a in rec_zone], dtype=np.int64)
    T["n_offset"] = n_offset
    T["state"] = _state()
    return T


def join_trees(hist: dict, fut: dict) -> dict:
    """Concatenate a phase-1 history tree and a phase-2 continuation into one tree.

    Global indices already line up: phase 2 was told to start numbering at
    `hist['state']['next_gidx']`, so the frontier's recorded `parent` values point back
    into `hist` and every child index exceeds its parent's. That is the invariant the
    prune cascade relies on.
    """
    if hist.get("n", 0) == 0:
        return fut
    if fut.get("n", 0) == 0:
        return hist
    assert fut["n_offset"] == hist["n"], (fut["n_offset"], hist["n"])
    out = {}
    for k, v in hist.items():
        if isinstance(v, np.ndarray) and k != "gen_sizes":
            out[k] = np.concatenate([v, fut[k]])
    out["gen_sizes"] = np.concatenate([hist["gen_sizes"], fut["gen_sizes"]])
    out["n"] = int(hist["n"] + fut["n"])
    out["seed_n"] = hist["seed_n"]
    out["n_offset"] = 0
    out["hit_cap"] = bool(hist["hit_cap"] or fut["hit_cap"])
    out["n_hist"] = int(hist["n"])
    return out


def prune(T: dict, params: Params, scenario: dict | None, deploy_day: float) -> dict:
    """Counterfactual removal on a recorded tree.

    An intervention can only make isolation EARLIER and safe burial MORE likely, so the
    intervened tree is a SUBTREE of the recorded SQ tree and the counterfactual is
    evaluated by removal alone.

    `scenario` (from lib.build_scenario) carries per-zone arrays:
        applies      (Z,) bool  — zones the intervention touches
        pcr_prob     (Z,) float — counterfactual PCR probability
        turnaround   (Z,) float — counterfactual lab turnaround (days)
        onsite       (Z,) bool  — machine in-zone (fast collection delay)
        local        (Z,) bool  — within a lab catchment
        sdb_zones    (Z,) bool  — zones where SDB coverage is raised
        sdb_coverage float      — target SDB coverage in those zones
    `deploy_day` gates the intervention in time: it only touches infections whose
    ONSET falls on or after that day.

    Returns dict with `removed` (n,) bool plus the counterfactual confirm/iso arrays.
    """
    n = int(T.get("n", 0))
    if n == 0:
        return {
            "removed": np.zeros(0, bool),
            "confirm_abs": np.zeros(0),
            "iso_cutoff": np.zeros(0),
            "safe_burial": np.zeros(0, bool),
        }

    zi = T["zone_idx"]
    onset = T["t_infect"] + T["incub"]

    # ---- counterfactual detection inputs, spliced by (zone in scope) & (onset >= deploy)
    if scenario is None:
        applies = np.zeros(n, bool)
        turnaround, pcr_prob = T["turnaround"], T["pcr_prob"]
        onsite, local = T["machine_high"], T["local"]
        sdb_hit = np.zeros(n, bool)
        sdb_cov = float(params.cadaver_swab_coverage)
    else:
        applies = scenario["applies"][zi] & (onset >= deploy_day)
        # MONOTONICITY GUARDS. An intervention must never leave a zone worse off than
        # SQ (operationally you would simply not use the new route). Without these, a
        # zone already inside a fast existing catchment could be handed a SLOWER
        # shipping turnaround, making iso_cutoff LATER and "averted" negative — an
        # artifact that would masquerade as a placement result. With them, the tree
        # under intervention is guaranteed a subtree of the SQ tree.
        turnaround = np.where(
            applies, np.minimum(scenario["turnaround"][zi], T["turnaround"]), T["turnaround"]
        )
        pcr_prob = np.where(
            applies, np.maximum(scenario["pcr_prob"][zi], T["pcr_prob"]), T["pcr_prob"]
        )
        onsite = np.where(applies, scenario["onsite"][zi] | T["machine_high"], T["machine_high"])
        local = np.where(applies, scenario["local"][zi] | T["local"], T["local"])
        sdb_hit = scenario["sdb_zones"][zi] & (onset >= deploy_day)
        sdb_cov = float(scenario["sdb_coverage"])

    u = {k: T[f"u_{k}"] for k in U_KEYS}
    args = (
        params,
        n,
        T["incub"],
        T["died"],
        T["otd"],
        T["trec"],
        T["t_infect"],
        turnaround,
        pcr_prob,
        onsite,
        local,
        u,
    )

    iso_base, safe_burial, t_confirm, got_pcr, _tp, _ei, _tc = _nuanced_iso_burial(*args)

    # cadaver_swab_coverage is a scalar on Params, so the raised-SDB arm is obtained by
    # a second elementwise call and spliced in. Both calls share the counterfactual
    # detection arrays, so they differ ONLY in coverage.
    if sdb_hit.any() and sdb_cov > float(params.cadaver_swab_coverage):
        import dataclasses

        p_hi = dataclasses.replace(params, cadaver_swab_coverage=sdb_cov)
        ib2, sb2, tc2, gp2, _, _, _ = _nuanced_iso_burial(p_hi, *args[1:])
        iso_base = np.where(sdb_hit, ib2, iso_base)
        safe_burial = np.where(sdb_hit, sb2, safe_burial)
        t_confirm = np.where(sdb_hit, tc2, t_confirm)
        got_pcr = np.where(sdb_hit, gp2, got_pcr)

    # Optional isolation-effectiveness override, for ceiling / attribution analysis.
    # MUST be spliced by `applies` exactly like the SDB coverage above. Passing a modified
    # `params` straight to prune() instead would apply the override to EVERY infection
    # including the whole pre-cutoff history, which is not a counterfactual at all -- it
    # made a "perfect isolation" arm avert 255% of the post-cutoff deaths that existed.
    if scenario is not None and scenario.get("iso_boost"):
        import dataclasses

        p_iso = dataclasses.replace(params, **scenario["iso_boost"])
        ib3, sb3, tc3, gp3, _, _, _ = _nuanced_iso_burial(p_iso, *args[1:])
        iso_base = np.where(applies, ib3, iso_base)
        safe_burial = np.where(applies, sb3, safe_burial)
        t_confirm = np.where(applies, tc3, t_confirm)
        got_pcr = np.where(applies, gp3, got_pcr)

    # ---- generation-wise forward pass: tracing depends on the PARENT's confirm time,
    # and removal cascades from parent to child. Parent is always in an earlier block.
    removed = np.zeros(n, bool)
    iso_cutoff = iso_base.copy()
    confirm_abs = T["t_infect"] + t_confirm
    parent = T["parent"]
    gi, is_bur = T["gi"], T["is_bur"]
    u_trace = T["u_trace"]
    trace_eff, trace_lag = float(params.sq_trace_eff), float(params.sq_trace_lag)

    bounds = np.concatenate([[0], np.cumsum(T["gen_sizes"])])
    for g in range(len(T["gen_sizes"])):
        lo, hi = int(bounds[g]), int(bounds[g + 1])
        if lo >= hi:
            continue
        if g == 0:
            tcut = np.full(hi - lo, np.inf)
        else:
            par = parent[lo:hi]
            par_conf = confirm_abs[par]
            traced = np.isfinite(par_conf) & (u_trace[lo:hi] < trace_eff)
            tcut = np.where(traced, par_conf + trace_lag, np.inf)
            # cascade: a removed parent's offspring never happen
            par_removed = removed[par]
            # keep-test against the parent's COUNTERFACTUAL isolation / burial
            keep = np.where(is_bur[lo:hi], ~safe_burial[par], gi[lo:hi] < iso_cutoff[par])
            # Defensive causal gate: an intervention cannot prevent a transmission that
            # already happened. This is PROVABLY REDUNDANT for any scenario-based arm --
            # offspring are infected at parent_tinf + incub + s with s >= 0, i.e. always at
            # or after the parent's ONSET, so `applies` (onset >= deploy_day) already
            # implies offspring t_infect >= deploy_day. Verified empirically: adding this
            # changed every reported arm by 0.0%. Kept only as a guard against a future
            # scenario key that bypasses the onset gate (as a raw `params` override does --
            # see the iso_boost path below, which is spliced precisely to avoid that).
            if scenario is not None and np.isfinite(deploy_day):
                keep = keep | (T["t_infect"][lo:hi] < deploy_day)
            removed[lo:hi] = par_removed | ~keep
        iso_cutoff[lo:hi] = np.minimum(iso_base[lo:hi], tcut - T["t_infect"][lo:hi])
        # a removed infection cannot confirm, so it cannot trace its own offspring
        if g > 0:
            confirm_abs[lo:hi] = np.where(removed[lo:hi], np.inf, confirm_abs[lo:hi])

    return {
        "removed": removed,
        "confirm_abs": confirm_abs,
        "iso_cutoff": iso_cutoff,
        "safe_burial": safe_burial,
        "got_pcr": got_pcr,
        "applies": applies,
    }


def tree_to_frame(
    T: dict, params: Params, confirm_capacity=None, queue_query_days=None
) -> pd.DataFrame:
    """Rebuild the exact `model.simulate` observation-layer DataFrame from a tree.
    Used to check that `simulate_tree` and `simulate` agree."""
    if T.get("n", 0) == 0:
        return pd.DataFrame(
            columns=[
                "zone_idx",
                "care_zone",
                "referred",
                "t_infect",
                "onset",
                "t_detect",
                "detected",
                "died",
                "t_death",
                "isolated",
                "iso_start",
                "iso_end",
                "hit_cap",
            ]
        )
    t_arrive = T["sq_confirm_abs"]
    detected = np.isfinite(t_arrive)
    queue_at_query = None
    if confirm_capacity is not None:
        t_detect = np.full(t_arrive.size, np.inf)
        sel = detected & np.isfinite(t_arrive)
        if queue_query_days is not None:
            t_detect[sel], queue_at_query = _confirm_with_capacity(
                t_arrive[sel],
                confirm_capacity[0],
                confirm_capacity[1],
                queue_query_days=queue_query_days,
            )
        else:
            t_detect[sel] = _confirm_with_capacity(
                t_arrive[sel], confirm_capacity[0], confirm_capacity[1]
            )
    else:
        t_detect = t_arrive
    onset = T["t_infect"] + T["incub"]
    df = pd.DataFrame(
        {
            "zone_idx": T["zone_idx"],
            "care_zone": T["care_zone"],
            "referred": T["referred"],
            "t_infect": T["t_infect"],
            "onset": onset,
            "t_detect": t_detect,
            "detected": detected,
            "died": T["died"],
            "t_death": onset + T["otd"],
            "isolated": T["sq_isolated"],
            "iso_start": T["sq_iso_start"],
            "iso_end": T["sq_iso_end"],
            "hit_cap": T["hit_cap"],
        }
    )
    if queue_query_days is not None:
        df.attrs["queue_at_query"] = (
            queue_at_query if queue_at_query is not None else np.zeros(len(queue_query_days))
        )
        df.attrs["queue_query_days"] = np.asarray(queue_query_days)
    return df
